// Protocol revision 3 mock. Tests inspect actual page requests, not UI helpers.
const snapshot={threadId:'t',cwd:'/project',name:'Test',model:'local/m',effort:'off',efforts:['off','high','stale-effort'],busy:false,eventId:10,serverInstanceId:'s',contextTokens:4,hasMore:true,before:'t-i1',items:[{id:'t-i1',type:'agentMessage',text:'Initial',entryId:'entry1'},{id:'t-i2',type:'uiBlock',uiId:'ext/block',rev:4,tree:{type:'Text',props:{text:'Extension transcript block'}}}],ui:{version:1,instances:[{site:'pane',id:'atto/diff',rev:2,options:{title:'Diff'},tree:{type:'Diff',props:{source:'-old\n+new'}}},{site:'band',id:'ext/band',rev:3,tree:{type:'Text',props:{text:'Above prompt'}}},{site:'status',id:'ext/status',rev:4,tree:{type:'Text',props:{text:'Status tree'}}}]} };
let eventId=20;globalThis.sent=[];
class FakeWS {
 static OPEN=1;
 constructor(url,protocols){this.url=url;this.protocols=protocols;this.readyState=1;globalThis.ws=this;queue.push(()=>this.onopen?.());}
 send(s){const m=JSON.parse(s);sent.push(m);if(m.id==null)return;let result={};switch(m.method){case 'initialize':result={clientId:'c',protocolVersion:3,serverInstanceId:'s'};break;case 'models/list':result={models:[{id:'local/m',name:'Local',efforts:['off','high'],hasKey:true,images:true}]};break;case 'thread/list':result={threads:[{threadId:'t',name:'Test',cwd:'/project',loaded:true},...(m.params.includeArchived?[{threadId:'child',name:'Child',cwd:'/worktree',archived:true,agent:{parentThreadId:'t',lifecycle:'closed'}},{threadId:'grandchild',name:'Grandchild',cwd:'/worktree',archived:true,agent:{parentThreadId:'child',lifecycle:'closed'}},{threadId:'other',preview:'# Other **task**',lastMessage:'| A | B |\n| --- | --- |\n| x | y |',cwd:'/other-project'}]:[])]};break;case 'thread/start':case 'thread/resume':case 'thread/read':result=JSON.parse(JSON.stringify(snapshot));break;case 'commands/list':result={commands:[{name:'diff',description:'Diff'},{name:'goal',description:'Goal'}]};break;case 'thread/items':result={items:[{id:'earlier',type:'userMessage',text:'Earlier'}],hasMore:false,before:'earlier'};break;case 'thread/setEffort':result={threadId:'t',effort:m.params.effort,model:'local/m',cwd:'/project',busy:false};break;case 'input/submit':result={status:'started'};queue.push(()=>{this.onmessage({data:JSON.stringify({method:'item/started',eventId:++eventId,params:{threadId:'t',item:{id:'t-i3',type:'agentMessage',status:'inProgress',text:''}}})});this.onmessage({data:JSON.stringify({method:'item/delta',eventId:++eventId,params:{threadId:'t',itemId:'t-i3',delta:'Hello'}})});});break;}
 queue.push(()=>this.onmessage?.({data:JSON.stringify({id:m.id,result})}));
 }
 close(){this.readyState=3;this.onclose?.();}
}
globalThis.WebSocket=FakeWS;
